user:
  outputs:
    default:
      job_execution_timeout_seconds: 300
      keyfile_json:
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        auth_uri: https://accounts.google.com/o/oauth2/auth
        client_email: ghany-zoomcamp@kestra-sandbox-490216.iam.gserviceaccount.com
        client_id: '105719021860388673149'
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/ghany-zoomcamp%40kestra-sandbox-490216.iam.gserviceaccount.com
        private_key: '-----BEGIN PRIVATE KEY-----

          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmzSfElbU6Eowb

          mN5vT7mzNE8eG4KhjTn5FFQC2aHzbEx88z8NHQiNq90zKd9VU096fgPQ0XH00cGf

          795h69Lo938b1Ll++luPVlEGw417uNu37duEiY1mhJ/M+9l9rksUy00HBCiYXvc3

          uzK2jHP5eKIu6xoFzsrPwn9/iTjKh9wxHRwz550cmFoQXn9L7V6tEckycMGzUzXY

          DFDLhXFuMsEWmjyDh+tUy3LJyvH20dC3tJSLPU6apzSgwkM8HETLone3I20c2KPL

          yHyjSPKLeO2BnSBC4KATPVvzMh4rn8sd+R6feQXpYxDjH/IwyJ7BJ3Qpe4dmeZCJ

          MQCCorjLAgMBAAECggEADgSsOhl03M0Qk68sySu+SRZ1LGwWde+nDCJjucZC60Yn

          mtFcnq8DzYLrTltPXDM/Y5Ax+juSpAckNTCqaWNcMIfAWdKZG61RwuxNAfsEVH4M

          OoXVzuqP2ipSPcl6v//FFUR4FEYKsrI50lK8EoXKUhCL3NKVt3WSK5TGigLlJXbT

          zMnr+Z5VKdWQRRLnhiseGoIetrtSciEtFCzo5tTpHHrACmyXL18ELbYjwfyLVyus

          23JjkuR+rye+UrK1NdB/+fHFIqtkjUY2U2E6clHIdMDU1qk+lY+r8O/rP6R4u8XT

          oYwUtLtoCe6kBpduQfBu2rD6vNbTMD9lQrPjkIsRUQKBgQDXTEf5Pxum9P/ZA6hS

          Y7efGhtkSKuT4/hdGjL3VleE6jSJ6tJBQkxu2US/DOH2KKh2hQq9/jKvc52MGPi4

          TGHNIQDka3FPsJjwpst+O/JSaWkVkV8nyIkCrQhGHPdD6iVkyBTloYU/gE4dVPpi

          FpWZshuDZ1MMmn3ChpZafOv/2wKBgQDGVcw/KtKCf6/FFsIvjZGeEH4YdjCtXeat

          c/x78xm1Q73tDzqkBdSMQmdkWm4D6eiu0r32cCjAjm0r4i4kwi08BU74ZBCosK9c

          jp4bT8FGXUtJRU2RiQ54zK1pVX7PnbyVOy/jB5F3cSU4mN62WGcl6fDQvCLaugP2

          Ifh8R4O10QKBgEEeM06xxb1TsOaEcq6otmsKzGoiiLKsavxN5khk9weehtGIEpvm

          X5PPZzmZveZkGb/vMXaRoebrQyWSj/e+Mn6GkuyDirwdn8R5zmaZ3wsKEtyRIYS4

          5KfIig4ayLbj5Pd8hMWHevPf7MB2aVytlAXult/Bqp7PQ2ZIqsUnr4GtAoGADMxa

          irTzspIUwI4QZ8sl22JLEL8Hsxg9G3JBl6n/PbAqYFK8QPtTVN2wGEyxjrUYW7ej

          pHRmXM6UAuHsgli5XIcnKmYioRANsNZPI4oI+cZpZkf/kmWatnbWtdZbgYA3PBX+

          qBLD80Ys1bMfo/qeZVbsQDvzr9OTD93vT+25dRECgYEAhQXGz3KbddeDxssq8yrC

          ZWz+11/52Gfx8P176G92v/+LOrbhQGd+fArOSRTD1Ee+kLcT/iUels1QpkdJHXzj

          i2He6ZFKxT0q1P0ofgAToCPe1u43RxxZQ0SVTlCJB3/teTEzuSqECiT1waMAxBEv

          PFgqYIcGkOxmMYpvPnALqOU=

          -----END PRIVATE KEY-----

          '
        private_key_id: 8deea07092095da717246dd2d4eb64658c2cba7f
        project_id: kestra-sandbox-490216
        token_uri: https://oauth2.googleapis.com/token
        type: service_account
      location: asia-southeast2
      maximum_bytes_billed: 1000000000
      method: service-account-json
      project: kestra-sandbox-490216
      schema: dbt_gsalam
      scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
      - https://www.googleapis.com/auth/userinfo.email
      target_name: default
      threads: 4
      type: bigquery
  target: default
